# All paths relative to Data directory

[core]

[font.main]
file=GUI/Fonts/DejaVuSans.ttf
size=36

[font.chat]
file=GUI/Fonts/DejaVuSans.ttf
size=16

[messagebox]
ok=(375,341,100,50)
text=(232,95,390,240)

[yesnobox]
yes=(325,341,100,50)
no=(430,341,100,50)
text=(232,95,390,240)

[button]
tex=GUI/Textures/button1.png
tex.selected=GUI/Textures/button1selected.png
tex.pressed=GUI/Textures/button1pressed.png

[textbox]
tex=GUI/Textures/textbox1.png
tex.selected=GUI/Textures/textbox1selected.png
tex.pressed=GUI/Textures/textbox1.png
cursor=GUI/Textures/textbox1cursor.png

[listbox]
tex=GUI/Textures/listbox1.png
border=GUI/Textures/listboxborder1.jpg

[healthbar]
tex=GUI/Textures/HealthBar.png
outlineWidth=1

