[core]

[font.main]
file=Data/GUI/Fonts/DejaVuSans.ttf
size=36

[font.chat]
file=Data/GUI/Fonts/DejaVuSans.ttf
size=16

[messagebox]
ok=(375,341,100,50)
text=(232,95,390,240)

[button]
tex=Data/GUI/Textures/button1.png
tex.selected=Data/GUI/Textures/button1selected.png
tex.pressed=Data/GUI/Textures/button1pressed.png

[textbox]
tex=Data/GUI/Textures/textbox1.png
tex.selected=Data/GUI/Textures/textbox1selected.png
tex.pressed=Data/GUI/Textures/textbox1.png
cursor=Data/GUI/Textures/textbox1cursor.png

[listbox]
tex=Data/GUI/Textures/listbox1.png
border=Data/GUI/Textures/listboxborder1.jpg

